apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: reconnaissance-apis
    - op: replace
      path: /metadata/labels/app
      value: reconnaissance-apis
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: reconnaissance
  target:
    name: apis
- patch: |-
    - op: replace
      path: /metadata/name
      value: reconnaissance-ui
    - op: replace
      path: /metadata/labels/app
      value: reconnaissance-ui
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: reconnaissance
  target:
    name: ui
- patch: |-
    - op: replace
      path: /spec/to/name
      value: reconnaissance-ui
  target:
    kind: Route
    name: ui
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value 
      value: reconnaissance-apis
    - op: replace
      path: /spec/selector/matchLabels/app
      value: reconnaissance-ui
    - op: replace
      path: /spec/template/metadata/labels/app
      value: reconnaissance-ui
  target:
    kind: Deployment
    name: ui
- patch: |-
    - op: replace
      path: /spec/selector/matchLabels/app
      value: reconnaissance-apis
    - op: replace
      path: /spec/template/metadata/labels/app
      value: reconnaissance-apis            
  target:
    kind: Deployment
    name: apis
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: reconnaissance-apis
  target:
    kind: Service
    name: apis
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: reconnaissance-ui
  target:
    kind: Service
    name: ui
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - system=reconnaissance - Reconnaissance Vehicles
  - app_name=reconnaissance